using Content.Client.Computer;
using Content.Client.UniversalElasticPort.BUI;
using Content.Client.UserInterface.Controls;
using Content.Shared.UniversalElasticPort.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UniversalElasticPort.UI;

[GenerateTypedNameReferences]
public sealed partial class UEPConsoleWindow : FancyWindow,
    IComputerWindow<UEPBoundUserInterfaceState>
{
    public UEPBoundUserInterface BUI = default!;

    public UEPConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(UEPBoundUserInterfaceState scc)
    {
        // RadarScreen.UpdateState(scc);
        AvailableConnectionsScroll.RemoveAllChildren();
        AvailablePortsScroll.RemoveAllChildren();

        AvailableConnectionsControl.Visible = scc.CurrentConnection == null;
        CurrentConnectionControl.Visible = scc.CurrentConnection != null;

        if (scc.CurrentConnection == null)
        {
            var i = 0;
            foreach (var conn in scc.AvailableConnections)
            {
                var child = new UEPAvailableConnectionRow(BUI, conn)
                {
                    PanelOverride = new StyleBoxFlat(i % 2 == 0 ? Color.FromHex("#222222") : Color.FromHex("#292929ff"))
                };
                AvailableConnectionsScroll.AddChild(child);
                i++;
            }
        }
        else
        {
            var i = 0;
            foreach (var port in scc.PlugStates)
            {
                var child = new UEPPlugCard(BUI, port.Value)
                {
                    PanelOverride = new StyleBoxFlat(i % 2 == 0 ? Color.FromHex("#222222") : Color.FromHex("#292929ff"))
                };
                AvailablePortsScroll.AddChild(child);
                i++;
            }

            // Disconnect logic
            DisconnectBtn.OnPressed += (args) =>
            {
                if (BUI == null) return;
                BUI.SendMessage(new UEPDisconnectMessage());
            };
        }
    }
}
