using Content.Client.UniversalElasticPort.BUI;
using Content.Shared.SensorMonitoring;
using Content.Shared.UniversalElasticPort.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UniversalElasticPort.UI;

[GenerateTypedNameReferences]
public sealed partial class UEPPowerStatusGrid : GridContainer
{
    public UEPPowerStatusGrid(UEPBoundUserInterface bui, UEPPowerPlugState plug, UEPPlugCard parent)
    {
        RobustXamlLoader.Load(this);

        LocalLoad.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedLoad);
        RemoteLoad.Text = parent.FormatValue(SensorUnit.PowerW, plug.RemoteState.CombinedLoad);

        LocalSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedSupply);
        RemoteSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedSupply);

        LocalMaxSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.LocalState.CombinedMaxSupply);
        RemoteMaxSupply.Text = parent.FormatValue(SensorUnit.PowerW, plug.RemoteState.CombinedMaxSupply);

    }

}
